language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kokiebisu/slack-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true kokiebisu/slack-test yarn test -- --coverage

after_success:
  - docker build -t kokiebisu/slack-client ./client
  - docker build -t kokiebisu/slack-nginx ./nginx
  - docker build -t kokiebisu/slack-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kokiebisu/slack-client
  - docker push kokiebisu/slack-nginx
  - docker push kokiebisu/slack-server

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: slack
  env: Slack
  bucket_name: elasticbeanstalk-us-east-1-776733965771
  bucket_path: slack
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
