language: generic
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kokiebisu/slack-web-dev -f ./web/dev.Dockerfile .

script:
  - docker run -e CI=true kokiebisu/slack-web-dev yarn test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
