language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kokiebisu/slack -f ./server/dev.Dockerfile .

script:
  - docker run -e CI=true kokiebisu/slack npm run test -- --coverage
