language: generic
sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t kokiebisu/slack-test -f ./web/dev.Dockerfile ./client

script:
  - docker run -e CI=true kokiebisu/slack-test yarn test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
