language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kokiebisu/slack -f dev.Dockerfile ./server

script:
  - docker run -e CI=true kokiebisu/slack npm run test -- --coverage
