language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kokiebisu/slack -f dev.Dockerfile .

script:
  - docker run -e CI=true kokiebisu/slack npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'slack test server'
  env: 'SlackTestServer-env'
  bucket_name: 'elasticbeanstalk-us-east-1-776733965771'
  bucket_path: 'slack test server'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
