version: '3.7'
services:
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: dev.Dockerfile
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - client
  #     - api
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=slackdb
      - POSTGRES_PORT=5432
  redis:
    image: redis:latest
  api:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=slackdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - redis
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: dev.Dockerfile
  #   stdin_open: true
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
volumes:
  database_postgres:
