version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slackdb
  redis:
    image: redis:latest
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - 80:80
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=slackdb
      - PGPASSWORD=postgres
      - PGPORT=5432
      - MAILSENDER=kokoaj.saas@gmail.com
      - MAILPASS=kronos111
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - NODE_ENV=development
