version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - slack
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - '8081:80'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - slack
    depends_on:
      - server
volumes:
  database_postgres:
