version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=slack-server
      - POSTGRES_PORT=5432
  redis:
    image: redis:latest
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=slack-server
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - 4000:4000
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
volumes:
  database_postgres:
