version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=slackdb
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - slack
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - slack
  api:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=slackdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis
    networks:
      - slack
  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - slack
volumes:
  database_postgres:

networks:
  slack:
    driver: bridge
