version: '3.7'
services:
  db:
    image: postgres
    env_file:
      - prod.env
    volumes:
      - database_postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - slack
  server:
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    depends_on:
      - db
      - redis
    # ports:
    #   - '4000:4000'
    networks:
      - slack
    volumes:
      - ./server:/root
    env_file:
      - prod.env
  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
    networks:
      - slack
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - slack
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - '8081:80'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - slack
    depends_on:
      - server
volumes:
  database_postgres:

networks:
  slack:
    driver: bridge
