version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: slackserver
    volumes:
      - database_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - slack
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'
    networks:
      - slack
  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
    networks:
      - slack
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - slack
    ports:
      - '3000:3000'
    volumes:
      - app/node_modules
      - ./client:/app
    stdin_open: true

volumes:
  database_postgres:

networks:
  slack:
    driver: bridge
