version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slackdb
    networks:
      - slack
  redis:
    image: redis:latest
    networks:
      - slack
  proxy:
    restart: always
    image: kokiebisu/slack-proxy
    ports:
      - 80:80
    networks:
      - slack
  server:
    image: kokiebisu/slack-server
    environment:
      - NODE_ENV=production
      - HOST=64.225.126.176
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=slackdb
      - PGPASSWORD=postgres
      - PGPORT=5432
      - MAILSENDER=kokoaj.saas@gmail.com
      - MAILPASS=kronos111
    networks:
      - slack
  client:
    image: kokiebisu/slack-client
    environment:
      - NODE_ENV=production
      - HOST=64.225.126.176
    networks:
      - slack

networks:
  slack:
