version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB}
    networks:
      - slack_network

  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - ./data/redis:/data
    networks:
      - slack_network

  server:
    build: server/
    image: slack_server
    ports:
      - 4000:4000
    environment:
      - POSTGRES_HOST=db
      - POSTGRSE_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    depends_on:
      - db
      - redis
    networks:
      - slack_network

networks:
  slack_network:
    driver: bridge
