version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=slackdb
  redis:
    image: redis:latest
  proxy:
    restart: always
    image: kokiebisu/slack-proxy
    ports:
      - 80:80
  server:
    image: kokiebisu/slack-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=slackdb
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    image: kokiebisu/slack-client
