version: 2
jobs:
  visual_testing:
    working_directory: ~/slack/web
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/slack
      - run:
          name: Installing dependencies
          command: yarn
      - run:
          name: Comparing snapshots
          command: yarn chromatic

workflows:
  version: 2
  tasks:
    jobs:
      - visual_testing
